language: python
sudo: false
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -f -b -p $PWD/miniconda3
  - export PATH=$PWD/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # install setup environment
  - bash install.sh
before_script:
  - echo 'oecophylla FTW!'
  # decompress test databases
  # these databases are huge when decompressed, and can fill up available disk space on Travis, so launch those test only when necessary
  # - bunzip2 test_data/kraken_test_db/database.idx.bz2
  # - bunzip2 test_data/shogun_test_db/phix.ctr.bz2
script:
  # run workflow
  - export PATH=$PATH:$PWD/utree
  - source activate oecophylla
  - pip install -e .
  - pip install nose
  - nosetests .
  - source deactivate
  - bash uninstall-conda-envs.sh
after_success:
  - coveralls
