abundance_samples:
- sample_S22282
- sample_S22205
assemblers:
- megahit
- metaspades
binning_samples:
- sample_S22282
- sample_S22205
envs:
  anvi: source activate oecophylla-anvi
  humann2: source activate oecophylla-humann2
  kraken: source activate oecophylla-kraken
  qc: source activate oecophylla-qc
  raw: source activate oecophylla-qc
  metaphlan2: source activate oecophylla-metaphlan2
  kraken: source activate oecophylla-kraken
  shogun: source activate oecophylla-shogun
  assemble: source activate oecophylla-assemble
  mash: source activate oecophylla-mash
mapping_assembler: metaspades
params:
  atropos: ' -a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A GATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGT
    -q 15 --minimum-length 100 --pair-filter any'
  humann2:
    humann2_aa_db: 'humann2_aa_db: /home/jgsanders/ref_data/humann2/uniref'
    humann2_nt_db: /home/jgsanders/ref_data/humann2/chocophlan
    metaphlan_dir: /home/jgsanders/share/metaphlan2
    norms:
    - cpm
    - relab
    other: ''
  kraken:
    # kraken_db: test_data/kraken_test_db
    kraken_db: /home/qiz173/Works/WoL/profiling/ref107/kraken
    bracken_db: /home/qiz173/Works/WoL/profiling/ref107/kraken/75mers_distr.txt
  maxbin: -plotmarker
  metaphlan2:
    # metaphlan2_dir: /home/jgsanders/git_sw/metaphlan2
    metaphlan2_db: test_data/mp2_test_db/mpa_v20_m200
  shogun: --utree_indx /home/qiz173/Databases/SHOGUN/annotated/utree/stdb.ctr
resources:
  centrifuge_base: /home/jgsanders/miniconda/envs/anvio2/centrifuge
  centrifuge_models: /home/jgsanders/miniconda/envs/anvio2/centrifuge/b+h+v/b+h+v
samples:
  sample_S22205:
    filter_db: ./test_data/phix
    forward:
    - ./test_data/test_reads/S22205_S104_L001_R1_001.fastq.gz
    reverse:
    - ./test_data/test_reads/S22205_S104_L001_R2_001.fastq.gz
  sample_S22282:
    filter_db: ./test_data/phix
    forward:
    - ./test_data/test_reads/S22282_S102_L001_R1_001.fastq.gz
    reverse:
    - ./test_data/test_reads/S22282_S102_L001_R2_001.fastq.gz
tmp_dir_root: ./
trimmer: atropos
