tmp_dir_root: ./

envs:
  anvi: source activate oecophylla-anvi
  humann2: source activate oecophylla-humann2
  kraken: source activate oecophylla-kraken
  qc: source activate oecophylla-qc
  raw: source activate oecophylla-qc
  metaphlan2: source activate oecophylla-metaphlan2
  kraken: source activate oecophylla-kraken
  shogun: source activate oecophylla-shogun
  assemble: source activate oecophylla-assemble
  distance: source activate oecophylla-distance

params:
  filter_db: ./test_data/phix
  atropos: ' -a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A GATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGT
    -q 15 --minimum-length 100 --pair-filter any'
  humann2:
    humann2_aa_db: 'humann2_aa_db: /home/jgsanders/ref_data/humann2/uniref'
    humann2_nt_db: /home/jgsanders/ref_data/humann2/chocophlan
    metaphlan_dir: /home/jgsanders/share/metaphlan2
    norms:
    - cpm
    - relab
    other: ''
  sourmash:
    sourmash_db: test/sourmash_test_db
    kmer: 31
    scaled: 10000
  mash:
    sketch_size: 1000
  metaphlan2:
    db: test_data/mp2_test_db/mpa_v20_m200
    # taxon name to TaxID dictionary
    name2tid: test_data/mp2_test_db/mpa_v20_m200.name2taxid
    levels: phylum,genus,species
    map: no
  kraken:
    db: test_data/kraken_test_db
    # Bracken kmer distribution file
    kmers: test_data/kraken_test_db/75mers_distr.txt
    # taxonomic ranks (kingdom to species) to reestimate abundance using Bracken
    levels: phylum,genus,species
    # whether to keep original mapping file
    map: no
  shogun:
    db: test_data/shogun_test_db
    # alignment algorithm: bowtie2, burst and utree
    aligner: utree
    # taxonomic ranks (kingdom to strain) to redistribute reads
    levels: phylum,genus,species
    # whether to keep original mapping file
    map: no
  maxbin: -plotmarker
resources:
  centrifuge_base: /home/jgsanders/miniconda/envs/anvio2/centrifuge
  centrifuge_models: /home/jgsanders/miniconda/envs/anvio2/centrifuge/b+h+v/b+h+v
samples:
  sample_S22205:
    forward:
    - ./test_data/test_reads/S22205_S104_L001_R1_001.fastq.gz
    reverse:
    - ./test_data/test_reads/S22205_S104_L001_R2_001.fastq.gz
  sample_S22282:
    forward:
    - ./test_data/test_reads/S22282_S102_L001_R1_001.fastq.gz
    reverse:
    - ./test_data/test_reads/S22282_S102_L001_R2_001.fastq.gz

